rocketmq:
  nameServerAddr: 10.251.76.180:9876;10.251.76.202:9876;10.251.76.164:9876;10.251.76.211:9876
  producer:
    groupName: base
    maxMessageSize: 131072
    sendMsgTimeout: 10000

server:
  port: 9001
  tomcat:
    threads:
      max: 200 # 连接池最大数量

spring:
  banner:
    image:
      location: classpath:1.jpg
  redis:
    cluster:
      nodes:
        - 10.251.76.39:7001
        - 10.251.76.39:7004
        - 10.251.76.21:7002
        - 10.251.76.21:7005
        - 10.251.76.22:7003
        - 10.251.76.22:7006
      max-redirects: 5
    password: mypassword

  cloud:
    consul:
      config:
        enabled: true
        format: yaml # consul上文件格式
        watch: # 配置监视功能，主要监视配置的改变
          enabled: true
          wait-time: 10
        # data-key: data # 设置对应的文件名称
        prefix: config # 设置对应的文件夹名称
    loadbalancer:
      ribbon:
        enabled: false

# 配置 springboot 监控（actutor）信息
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有节点
    health:
      sensitive: false #关闭过滤敏感信息
  endpoint:
    health:
      show-details: ALWAYS  #显示详细信息
      cache:
        time-to-live: 0

# 注意 ribbon 和 feign 配置是相互独立的，例如：二者同时配置了充实机制重试次数是二者笛卡尔积
# 配置 ribbon 客户端，参考CommonClientConfigKey参数配置
seckill:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #配置负载均衡策略
    ReadTimeout: 3000 #配置请求超时时间,单位毫秒
    OkToRetryOnAllOperations: true #对所有操作请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数


# 配置feign客户端，此处配置参考 FeignClientProperties
feign:
  client:
    config:
      seckill: # 要配置的 feign 客户端的名称
        loggerLevel: HEADERS #NONE(不打印日志),BASIC(生产配置打印基础日志),HEADERS(打印带请求头的日志),FULL(打印全量日志);
        connectTimeout: 1000 #连接超时时间
        readTimeout: 3000 #请求超时时间
  compression: # feign请求压缩
    request:
      enabled: true # 对 feign 请求进行压缩
      min-request-size: 2048 #配置压缩数据大小的下限，超过这个值启动压缩
      mime-types: text/xml,application/xml,application/json # 配置压缩支持的 MIME 类型
    response:
      enabled: true # 对 feign 返回进行压缩
  hystrix:
    enabled: true


# Hystrix 全局配置参照 HystrixPropertiesManager 属性类
hystrix:
  command:
#    default:
#      circuitBreaker:
#        enabled: true
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000
    # Hystrix 针对服务进行配置
    CloudFeignHystrixClient#getFeign():
      circuitBreaker:
        requestVolumeThreshold: 5 #bucker桶最小线程数
        sleepWindowInMilliseconds: 5 #断路时间
        errorThresholdPercentage: 50 #失败率超过多少触发断路
        enabled: true
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000

logging:
  level:
    com.zyy.seckill.client: debug
