rocketmq:
  nameServerAddr: 10.251.76.180:9876;10.251.76.202:9876;10.251.76.164:9876;10.251.76.211:9876
  producer:
    groupName: base
    maxMessageSize: 131072
    sendMsgTimeout: 10000

server:
  port: 9001
  tomcat:
    threads:
      max: 200 # 连接池最大数量

spring:
  banner:
    image:
      location: classpath:1.jpg
  redis:
    cluster:
      nodes:
        - 10.251.76.39:7001
        - 10.251.76.39:7004
        - 10.251.76.21:7002
        - 10.251.76.21:7005
        - 10.251.76.22:7003
        - 10.251.76.22:7006
      max-redirects: 5
    password: mypassword

  cloud:
    consul:
      config:
        enabled: true
        format: yaml # consul上文件格式
        watch: # 配置监视功能，主要监视配置的改变
          enabled: true
          wait-time: 10
        # data-key: data # 设置对应的文件名称
        prefix: config # 设置对应的文件夹名称
    loadbalancer:
      ribbon:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有节点
    health:
      sensitive: false #关闭过滤敏感信息
  endpoint:
    health:
      show-details: ALWAYS  #显示详细信息
      cache:
        time-to-live: 0

seckill:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #配置负载均衡策略
    ReadTimeout: 1 #配置请求超时时间,单位毫秒
    OkToRetryOnAllOperations: true #对所有操作请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数


